#!/bin/sh -
clear
# Miner por: JayDDee | CPUMiner-OPT v3.8.0
# Créditos: AndreasBlk, BYETFAST, Darkstilo, FENIX_LINUX e SSH TLS
# Editado por duferdias

# Este script foi desenvolvido para execução em ambiente Linux.
# Pode ser executado automaticamente junto com a inicialização do sistema.


bash=$(echo $BASH)

if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

wallet=$1
carteira_exemplo=YyyXXxx111YyyXXxx111YyyXXxx111YyyW

if [ "$1" = ""  ]
then
echo "			\033[41;1;37m Minerar Bitcoin $versao \033[0m "				
sleep
echo "\033[34m Forma de uso: \033[0m"
echo "sudo sh $0 \033[31m Carteira de Bitcoin \033[0m  \n "
echo "\033[33m Exemplo:\033[0m"
echo "sudo sh $0 \033[31m $carteira_exemplo \033[0m   \n"
exit 0
fi

echo "			\033[41;1;37m Minerar Bitcoin $versao \033[0m "	
sleep 1
echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
sleep 1
echo "\033[01;31m	  *Minerar Bitcoin  http://zpool.ca \033[0m   \n"

sleep 1
echo "\033[44;1;37mEste script irá baixar, compilar e instalar o CPUMiner-OPT v3.8.0.\033[0m "
echo "\033[44;1;37mAo término, a mineração iniciará automaticamente.\033[0m "
sleep 5
clear

echo "\033[44;1;37mAtualizando lista de pacotes...\033[0m "
sudo apt-get update > /dev/null
sleep 2
clear

echo "\033[44;1;37mInstalando dependências...\033[0m "
sudo apt-get install screen -y >/dev/null
sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev make autoconf automake -y > /dev/null
memsize=`free | awk '/Mem/ { print $2 }'`
swapsize=`free | awk '/Swap/ { print $2 }'`
if [ "$memsize" -lt "1000000" ]
then
 if [ "$swapsize" -eq "0" ]
 then
  echo "Foi detectado que você possui menos que 1GB de RAM"
  echo "Será criada uma partição SWAP de 1GB para que o CPUMiner-OPT seja compilado com sucesso"
  sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 > /dev/null
  sudo mkswap /var/swap.img > /dev/null
  sudo chmod 600 /var/swap.img
  sudo swapon /var/swap.img
 fi
fi
sleep 2
clear

echo "\033[44;1;37mBaixando CPUMiner-OPT v3.8.0...\033[0m "
sudo rm -r cpuminer-opt-3.8.0
wget -q https://github.com/JayDDee/cpuminer-opt/archive/v3.8.0.tar.gz
echo "\033[44;1;37mExtraindo CPUMiner-OPT v3.8.0...\033[0m "
tar -zxvf v3.8.0.tar.gz > /dev/null
cd cpuminer-opt-3.8.0
echo "\033[44;1;37mCompilando CPUMiner-OPT v3.8.0...(pode demorar um pouco)\033[0m "
./build.sh > /dev/null
ln ./cpuminer ../cpuminer
sleep 2
clear

echo "\033[01;32mInstalação e configuração concluídas com sucesso"
sleep 3
clear

echo "\033[44;1;37mA mineração será iniciada em uma nova sessão. Não feche a janela do console agora!\033[0m "
echo "\033[44;1;37mFeche a janela do web-console ou de seu aplicativo de acesso remoto somente\033[0m "
echo "\033[44;1;37mapós o início da mineração.\033[0m "
sleep 10
clear

echo "\033[01;41mInicializando mineração...\033[0m \n "
sleep 1
echo "\033[01;31mSCRIPT INICIA SCREEN AUTOMÁTICO..."
sleep 3
clear

echo "\033[37;41mAbrindo sessão, aguarde...\033[0m "
sleep 3
sudo screen -dmS zpool ./cpuminer -a yescrypt -o stratum+tcp://segredosminer.cf:6233 -u $wallet
sleep 1
clear

echo "\033[37;41mSua mineração foi iniciada! Para visualizar o processo digite o comando abaixo:\033[01;0m \n"
echo "\033[37;41mCOMANDO [screen -x zpool]\033[0m"
sleep 1
